### PR TITLE
`defmt-print`: Recover from decoding-errors

### LINKED ISSUE #559: defmt-print cannot recover from decoding errors
It look like `defmt-print` exits with an error when decoding fails, even if rzCOBS is used for the transport encoding. Since a framed transport allows recovering from such errors, we should make sure that `defmt-print` can do that.

### PR DESCRIPTION
**Pull request by Urhengulas**
This PR uses the new `StreamDecoder`-API in `defmt-print` and utilizes it to recover from decoding errors.

Fixes #559

### CODE REVIEW

File: print/src/main.rs [hunk 1]
```diff
@@ -51,58 +51,62 @@ fn main() -> anyhow::Result<()> {
...
-                }
+            match stream_decoder.decode() {
+                Ok(frame) => forward_to_logger(&frame, location_info(&locs, &frame, &current_dir)),
+                Err(DecodeError::UnexpectedEof) => break,
+                Err(DecodeError::Malformed) => match table.encoding() {
+                    // raw encoding doesn't allow for recovery. therefore we abort.
+                    Encoding::Raw => return Err(DecodeError::Malformed.into()),
+                    // rzcobs encoding allows recovery from decoding-errors. therefore we stop
+                    // decoding the current, corrupted, data and continue with new one
+                    Encoding::Rzcobs => break,
```
Comment (japaric) [inline print/src/main.rs:75]: I think this should be `continue` because may be more data cached in the `stream_decoder`. if there isn't then the next iteration will hit the `Eof` case (which will make the program fetch more data from stdin)

File: print/src/main.rs [hunk 2]
```diff
@@ -51,58 +51,62 @@ fn main() -> anyhow::Result<()> {
...
-                }
-                Err(defmt_decoder::DecodeError::UnexpectedEof) => break,
-                Err(defmt_decoder::DecodeError::Malformed) => {
-                    log::error!("failed to decode defmt data: {:x?}", frames);
-                    return Err(defmt_decoder::DecodeError::Malformed.into());
-                }
+            match stream_decoder.decode() {
+                Ok(frame) => forward_to_logger(&frame, location_info(&locs, &frame, &current_dir)),
+                Err(DecodeError::UnexpectedEof) => break,
+                Err(DecodeError::Malformed) => match table.encoding() {
```
Comment (japaric) [inline print/src/main.rs:70]: could you move the 'can this encoding recover?' logic into a method on the `Encoding` enum itself? I think consumers should not be deciding on the `Encoding` variant but rather the `defmt-decoder` library should provide them that information.

File: decoder/src/lib.rs [hunk 3]
```diff
@@ -119,7 +119,7 @@ struct BitflagsKey {
 }
 
 #[derive(Copy, Clone, Debug, PartialEq)]
-enum Encoding {
+pub enum Encoding {
```
Comment (japaric) [inline decoder/src/lib.rs:122]: although all of `defmt-decoder` is unstable making this enum public is a semver hazard because now adding a variant is a breaking change in the API and that requires a semver bump. could you add a `#[non_exhaustive]` attribute here to prevent that potential issue?

(we could even go further and prevent matching on the enum by hiding it inside a newtype `pub struct Encoding(EncodingKind); enum EncodingKind { .. }` but that may be overkill)

**Review by japaric — COMMENTED** [review]
changes look good. left some suggestions

File: decoder/src/lib.rs (hunk 3 above)
Comment (Urhengulas) [reply decoder/src/lib.rs:123]: > could you add a `#[non_exhaustive]` attribute here to prevent that potential issue?

Done!

File: print/src/main.rs (hunk 2 above)
Comment (Urhengulas) [reply print/src/main.rs]: 👍🏾

File: print/src/main.rs (hunk 1 above)
Comment (Urhengulas) [reply print/src/main.rs]: 👍🏾

File: decoder/src/lib.rs [hunk 4]
```diff
@@ -136,6 +137,15 @@ impl FromStr for Encoding {
     }
 }
 
+impl Encoding {
+    pub const fn recoverable(&self) -> bool {
```
Comment (japaric) [inline decoder/src/lib.rs:141]: nit: naming convention (style?) is to name this `is_recoverable` (or maybe `can_recover`) when the method returns a `bool`

File: print/src/main.rs [hunk 5]
```diff
@@ -51,58 +51,61 @@ fn main() -> anyhow::Result<()> {
...
-                }
-                Err(defmt_decoder::DecodeError::UnexpectedEof) => break,
-                Err(defmt_decoder::DecodeError::Malformed) => {
-                    log::error!("failed to decode defmt data: {:x?}", frames);
-                    return Err(defmt_decoder::DecodeError::Malformed.into());
-                }
+            match stream_decoder.decode() {
+                Ok(frame) => forward_to_logger(&frame, location_info(&locs, &frame, &current_dir)),
+                Err(DecodeError::UnexpectedEof) => break,
+                Err(DecodeError::Malformed) => match table.encoding().recoverable() {
```
Comment (japaric) [inline print/src/main.rs:70]: (probably down to personal preference but `if boolean` is more common than `match boolean` IMO)

**Review by japaric — APPROVED** [review]
:+1:  Thanks! Feel free to send to bors with nits addressed or unaddressed

File: decoder/src/lib.rs (hunk 4 above)
Comment (Urhengulas) [reply decoder/src/lib.rs:141]:
```suggestion
    pub const fn can_recover(&self) -> bool {
```

File: print/src/main.rs (hunk 5 above)
Comment (Urhengulas) [inline print/src/main.rs:70]:
```suggestion
                Err(DecodeError::Malformed) => match table.encoding().can_recover() {
```

Comment (Urhengulas) [reply print/src/main.rs]: I think it is more common to use if. But match saves one line 😋

**Comment by Urhengulas** [comment]
bors retry
